services:
  server:
    container_name: bazelbot-server
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./src/data:/app/src/data
    depends_on:
      ollama-pull:
        condition: service_completed_successfully
      db:
        condition: service_healthy
  migration:
    build: .
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/data:/app/src/data
  ollama-pull:
    image: docker/genai:ollama-pull
    env_file:
      - .env
  ollama:
      image: ollama/ollama:latest
      ports:
        - "11434:11434"
      volumes:
        - ollama_volume:/root/.ollama
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bazelbot_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=bazelbot-db-1
      - ADMINER_DEFAULT_USERNAME=postgres
      - ADMINER_DEFAULT_DATABASE=bazelbot_db
volumes:
  db-data:
  ollama_volume:
