services:
  migration:
    container_name: bazelbot-test-migration
    build:
      context: .
      dockerfile: Dockerfile.test
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: bazelbot-test-db
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bazelbot_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    container_name: bazelbot-test-adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=bazelbot-test-db
      - ADMINER_DEFAULT_USER=postgres
      - ADMINER_DEFAULT_DATABASE=bazelbot_db
volumes:
  db-data: