services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: alembic upgrade head
    env_file:
      - .env
    environment:
    - DB_CONNECTION_URL=postgresql+psycopg2://postgres:postgres@bazelbot-db-1:5432/bazelbot_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
  db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bazelbot_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=bazelbot-db-1
      - ADMINER_DEFAULT_USERNAME=postgres
      - ADMINER_DEFAULT_DATABASE=bazelbot_db
volumes:
  db-data: