"""Create initial migration

Revision ID: 5cfa69fff879
Revises: 
Create Date: 2024-05-13 11:18:49.121704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5cfa69fff879"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bazels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=512), nullable=True),
        sa.Column("create_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bazels")
    # ### end Alembic commands ###
